plugins {
    id 'java-gradle-plugin'
    id 'java'
    id 'com.gradle.plugin-publish'
    id 'nrlssc.gradle'
}


compileJava.options.encoding = 'UTF-8'

sourceSets {
    main {
        java {
            srcDir 'src'
        }
        resources {
            srcDir 'resources'
        }
    }
}

clean {
    delete "libs"
}



jar {
    manifest {
        attributes 'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Main-Class': 'nrlssc.copyright.AddCopyright'
    }

}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'com.google.guava:guava:33.4.8-jre',           // Google guava
            'org.slf4j:slf4j-api:1.7.21'                // Logging via SLF4J

    runtimeOnly 'ch.qos.logback:logback-classic:1.1.7'

    testImplementation 'junit:junit:4.11'
}


// declare artifacts for generation and potential upload
artifacts {
    archives appZip
}

gradlePlugin {
    website = 'https://geoint.nrlssc.org/'
    vcsUrl = 'https://github.com/seanrl/add-copyright.git'
    //noinspection GroovyAssignabilityCheck
    plugins {
        copyrightLib {
            tags = ['copyright']
            id = 'nrlssc.add-copyright'
            displayName = 'add-copyright'
            description = 'This is not a plugin, just a library needed for other nrlssc plugins'
            implementationClass = 'nrlssc.copyright.AddCopyright'
        }
    }
}
